<?php

/**
 * @var \Artera\Customer\Block\Display $block
 */

echo $block->accepttnc();
?>
<html>
<form class="form form-logins"
      action="http://10.16.16.139/magento/tnc/account/check"
      method="post"
      id="logins-form"
      data-mage-init='{"validation":{}}'>
    <div class="privacy-container">
        <p><?php echo $block->getContent('terms-and-conditions');?></p>
        <div class="checkbox-container">
            <input type="checkbox"
                   id="<?php echo $block->getNameInLayout(); ?>"
                   name="login[logincustomer_account_login_privacy_included]"
                   value="1"
                   title="Accept Terms and Conditions"
                   class="checkbox"
                   data-validate="{required:true}"/>
            <label for="<?php echo $block->getNameInLayout(); ?>">
                <span>Accept Terms and Conditions</span>
            </label>
        </div>


        <div class="actions-toolbar">
            <div class="primary"><button type="submit" class="action login primary" name="sends" id="send2s"><span><?= $block->escapeHtml(__('I Agree')) ?></span></button></div>
        </div>

    </div>
</form>
</html>
